steps:
- task: NexPloitScan@3
  inputs:
    apiToken: 'w0kajfx.nexa.e2vkg66ovl2mxdqb0mheziwkme173u8r'
    hostname: 'nexploit.app'
    module: 'dast'
    discoveryTypes: 'crawler'
    crawlerUrls: 'https://brokencrystals.com'
    scanTests: 'angular_csti,jwt,date_manipulation,cookie_security,csrf,directory_listing,dom_xss,file_upload,full_path_disclosure,header_security,http_method_fuzzing,secret_tokens,version_control_systems,wordpress'