# Starter pipeline
- task: NexPloitScan@3
  inputs:
    apiToken: 'w0kajfx.nexa.e2vkg66ovl2mxdqb0mheziwkme173u8r'
    hostname: 'nexploit.app'
    module: 'dast'
    discoveryTypes: 'crawler'
    crawlerUrls: 'https://github.com/PauloSilvaNova8/brokencrystals'
    scanTests: 'angular_csti,jwt,date_manipulation,cookie_security,csrf,directory_listing,dom_xss,file_upload,full_path_disclosure,header_security,http_method_fuzzing,secret_tokens,version_control_systems,wordpress'
- task: NexPloitScan@3
  inputs:
    apiToken: 'w0kajfx.nexa.e2vkg66ovl2mxdqb0mheziwkme173u8r'
    hostname: 'nexploit.app'
    module: 'dast'
    discoveryTypes: 'crawler'
    scanTests: 'angular_csti,jwt,date_manipulation,cookie_security,csrf,directory_listing,dom_xss,file_upload,full_path_disclosure,header_security,http_method_fuzzing,secret_tokens,version_control_systems,wordpress'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
